# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac38ce8b68baceb5fb8ae8911f66b68b4624429326fae8180ed93b26b3a897087b22232107b849087570481cea620d9501fdc09cd1fec3138b98997b2a7ce837

test:
  secret_key_base: 882a478cf1fdacf6521bf9e18e4d9305552dcf18278f2b7182bfda17689e21912618c20d01ceccb60497a442ef86354c51af90125b4bc2b99747d588a8351c64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
